name: CV pdf builder

on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4

      # Compile document in docker container
       - name: Compile LaTeX document
         uses: xu-cheng/texlive-action@v3
         with:
            os: debian
       - name: Install system dependencies
         run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            latexmk --version || echo "KO"
            apt-get install -y qpdf
            latexmk --version || echo "KO"

       - name: Build .pdf and place them in release folder
         run: |
          make pdf
          cp *pdf ./release/

       - name: GH Release
         uses: softprops/action-gh-release@v2.0.8
         with:
          files: "./release/*.pdf"
          generateReleaseNotes: true
