name: CV pdf builder

on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install texlive-full -y
          tlmgr install   \
          l3kernel \
          l3packages \
          listings \
          pgf \
          tools \
          graphics \
          xkeyval \
          hyperref \
          xcolor \
          cleveref \
          etoolbox \
          oberdiek \
          ifxetex \
          ifluatex \
          tools \
          url \
          parskip \
          xstring \
          fontspec \
          fontawesome5 \
          lipsum \
          zapfding \
          luaotfload \
          cjk \
          xecjk \
          fandol \
          dvipdfmx \
          pdfescape \
          letltxmacro \
          luatexbase \
          ctex \
          bitset

      - name: Build .pdf and place them in release folder
        run: |
          make pdf
          cp *pdf ./release/
      - name: GH Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: "./release/*.pdf"
          generateReleaseNotes: true
